const express = require("express");
const dotenv=require("dotenv");
const cors=require("cors");
const app = express();
const user_route=require("./src/routes/user-routes");
const trip_routes = require('./src/routes/trip-routes');
const tracking_routes = require('./src/routes/tracking-routes');
const budget_routes = require('./src/routes/budget-routes');
const checkpoint_routes = require('./src/routes/checkpoint-routes');
const post_routes = require('./src/routes/post-routes');
const like_routes = require('./src/routes/like-routes');
const comment_routes = require('./src/routes/comment-routes');

app.use(cors());
app.use(express.json());
dotenv.config();
app.use('/api/v1/user',user_route);
app.use('/api/v1/trips', trip_routes);
app.use('/api/v1/tracking', tracking_routes);
app.use('/api/v1/budgets', budget_routes);
app.use('/api/v1/checkpoints', checkpoint_routes);
app.use('/api/v1/posts', post_routes);
app.use('/api/v1/likes', like_routes);
app.use('/api/v1/comments', comment_routes);
module.exports=app;