const express = require("express");
const dotenv=require("dotenv");
const cors=require("cors");
const app = express();
const user_route=require("./src/routes/user-routes");
app.use(cors());
app.use(express.json());
dotenv.config();
app.use('/api/v1/user',user_route);
module.exports=app;