const hiddenPlacesInIndia = [
    {
        name: "Mechuka Valley",
        location: "Arunachal Pradesh",
        about: "A picturesque valley near the Indo-China border, known for its lush greenery, wooden houses, and snow-capped mountains.",
        bestTimeToVisit: "October to April",
        imageUrl: "/images/HIDDEN/Mechuka.jpg",
    },
    {
        name: "Laitlum Canyons",
        location: "Meghalaya",
        about: "A breathtaking viewpoint offering panoramic views of deep gorges and misty hills, perfect for nature lovers and photographers.",
        bestTimeToVisit: "September to May",
        imageUrl: "/images/HIDDEN/Laitlum.cms",
    },
    {
        name: "Ziro Valley",
        location: "Arunachal Pradesh",
        about: "A tranquil valley known for its lush green rice fields, pine forests, and the indigenous Apatani tribe's unique culture.",
        bestTimeToVisit: "March to October",
        imageUrl: "/images/HIDDEN/Ziro.jpg",
    },
    {
        name: "Mawlynnong",
        location: "Meghalaya",
        about: "Dubbed as the cleanest village in Asia, this beautiful village offers tree houses, root bridges, and eco-friendly tourism.",
        bestTimeToVisit: "June to September",
        imageUrl: "/images/HIDDEN/mawly.jpeg",
    },
    {
        name: "Chopta",
        location: "Uttarakhand",
        about: "A hidden Himalayan gem known as the 'Mini Switzerland of India,' perfect for trekking, bird watching, and peaceful retreats.",
        bestTimeToVisit: "March to June & September to November",
        imageUrl: "/images/HIDDEN/chopta.jpg",
    },
    {
        name: "Tawang",
        location: "Arunachal Pradesh",
        about: "A scenic town housing the famous Tawang Monastery, high-altitude lakes, and beautiful snow-covered landscapes.",
        bestTimeToVisit: "March to June & September to November",
        imageUrl: "/images/HIDDEN/tawang.png",
    },
    {
        name: "Sandakphu",
        location: "West Bengal",
        about: "The highest peak in West Bengal, offering stunning views of the world's four tallest peaks including Everest and Kanchenjunga.",
        bestTimeToVisit: "October to April",
        imageUrl: "/images/HIDDEN/sandakpu.webp",
    },
    {
        name: "Majuli",
        location: "Assam",
        about: "The world's largest river island, known for its vibrant culture, monasteries, and breathtaking sunrise and sunset views.",
        bestTimeToVisit: "October to March",
        imageUrl: "/images/HIDDEN/majuli.jpg",
    },
    {
        name: "Gokarna",
        location: "Karnataka",
        about: "A peaceful coastal town known for its pristine beaches, spiritual aura, and laid-back vibe, often called the quieter alternative to Goa.",
        bestTimeToVisit: "October to March",
        imageUrl: "/images/HIDDEN/gokarna.jpg",
    },
    {
        name: "Chandratal Lake",
        location: "Himachal Pradesh",
        about: "A mesmerizing high-altitude lake with crystal-clear waters reflecting the surrounding snow-clad peaks, perfect for trekkers.",
        bestTimeToVisit: "June to September",
        imageUrl: "/images/HIDDEN/chandratal.webp",
    },
    {
        name: "Hemis",
        location: "Ladakh",
        about: "A remote Buddhist town famous for the Hemis Monastery and its vibrant annual festival celebrating Ladakhi culture.",
        bestTimeToVisit: "May to September",
        imageUrl: "/images/HIDDEN/hemis.webp",
    },
    {
        name: "Lepchajagat",
        location: "West Bengal",
        about: "A hidden hamlet near Darjeeling, offering mesmerizing views of Kanchenjunga and dense pine forests.",
        bestTimeToVisit: "October to April",
        imageUrl: "/images/HIDDEN/lepcha.jpg",
    },
    {
        name: "Lonar Crater Lake",
        location: "Maharashtra",
        about: "A unique saline soda lake formed due to a meteorite impact, surrounded by lush greenery and ancient temples.",
        bestTimeToVisit: "October to March",
        imageUrl: "/images/HIDDEN/lonarlake.jpg",
    },
    {
        name: "Dhanushkodi",
        location: "Tamil Nadu",
        about: "An abandoned ghost town at the southern tip of India, offering surreal beachscapes and the mythological Ram Setu viewpoint.",
        bestTimeToVisit: "October to March",
        imageUrl: "/images/HIDDEN/dhanushkodi.jpg",
    },
    {
        name: "Mokokchung",
        location: "Nagaland",
        about: "A culturally rich town known as the ‘Land of Festivals,’ showcasing vibrant Naga traditions and stunning landscapes.",
        bestTimeToVisit: "November to April",
        imageUrl: "/images/HIDDEN/mokochund.jpg",
    },
    {
        name: "Kanha National Park",
        location: "Madhya Pradesh",
        about: "The inspiration behind 'The Jungle Book,' this national park is home to Bengal tigers, leopards, and diverse wildlife.",
        bestTimeToVisit: "October to June",
        imageUrl: "/images/HIDDEN/nationalpark.jpg",
    },
    {
        name: "Bundi",
        location: "Rajasthan",
        about: "A lesser-known heritage town featuring blue houses, stunning palaces, and step-wells dating back to medieval times.",
        bestTimeToVisit: "October to March",
        imageUrl: "/images/HIDDEN/bundi.jpg",
    },
    {
        name: "Chembra Peak",
        location: "Kerala",
        about: "A mesmerizing trek leading to a heart-shaped lake at the top, surrounded by lush tea plantations and misty hills.",
        bestTimeToVisit: "September to March",
        imageUrl: "/images/HIDDEN/chembra.jpg",
    },
    {
        name: "Arvalem Caves",
        location: "Goa",
        about: "Ancient rock-cut caves with Buddhist and Hindu influences, offering a glimpse into Goa’s hidden historical gems.",
        bestTimeToVisit: "November to March",
        imageUrl: "/images/HIDDEN/caves.webp",
    },
];

export default hiddenPlacesInIndia;
